#!/bin/bash
# Common Raspberry pi configuration steps
#
##########################    SET SPANISH KEYBOARD    ##########################
echo "*** Setting Spanish keyboard at $TARGET"
TARGET="/etc/default/keyboard"
#
cat > $TARGET <<- EOF
# generated by smate setup script
XKBMODEL=pc105
XKBLAYOUT=es
XKBVARIANT=es
XKBOPTIONS=
BACKSPACE=guess
EOF
#
echo
#
#
###############################   SET US LOCALE  ###############################
echo "*** Setting US locale at $TARGET"
TARGET="/etc/default/locale"
#
cat > $TARGET <<- EOF
# generated by smate setup script
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
LANGUAGE=en_US.UTF-8
EOF
#
echo
#
#
###########################   SET MADRID TIMEZONE   ############################
echo "*** Setting Madrid Timezone"
#
sudo timedatectl set-timezone Europe/Madrid
echo
#
#
##############################  SET WIFI COUNTRY  ##############################
echo "*** Set ES wifi country"
TARGET="/etc/wpa_supplicant/wpa_supplicant.conf"
# this is not permanently set on raspi when using raspi-config
# raspi-config does not modify /etc/default/crda
# my raspi 4 seems to work OK without this setting
# see https://www.raspberrypi.org/forums/viewtopic.php?t=260974
# sudo iw reg set ES
#
# In wpa_supplicant, however there is a country setup
# Stellarmate comes with country=KW
sudo sed -i "s/country=[A-Z]*/country=ES/g" $TARGET        
echo
#
#
###########################  SET SCREEN RESOLUTION  ############################
# 1920x1080 60Hz 1080p-> group 2, mode 82   
# https://www.raspberrypi.org/documentation/configuration/config-txt/video.md
echo "Seting screen resolution to 1920x1080"
TARGET="/boot/config.txt"
#
# -i    -> case insensitive
#  s    -> substitute
#  ^    -> start of line
#  \#\? -> zero or one '#'
#  .\?  -> zero or one character (to catch a space after '#')
#  .*$  -> any number of chars before end-of-line
#  g -> greedy
sed -i "s/^\#\?.\?hdmi_group:0=.*$/hdmi_group:0=2/g" $TARGET
sed -i "s/^\#\?.\?hdmi_mode:0=.*$/hdmi_mode:0=82/g" $TARGET
#
echo
#
#
############################  SET CPU TEMPERATURE  #############################
echo "Setting CPU Temperature Widget"
TARGET="/home/stellarmate/.config/lxpanel/LXDE-pi/panels/panel"
#
# cat >>  --> append
cat >> $TARGET <<- EOF
Plugin {
  type=cputemp
  config {
  }
}
EOF
#
echo
#
#
############################### REMOVE BLUETOOTH ###############################
echo "Disable BlueTooth"
TARGET="/boot/config.txt"
#  
cat >> $TARGET <<- EOF
dtoverlay=disable-bt
EOF
#
echo
#
################################# INSTALL CHRONY #################################
echo "Install chrony"
sudo apt install chrony
#
echo "Setup chrony.conf"
TARGET="/etc/chrony/chrony.conf"
#
if [ "$RPITYPE" = "slave" ]
then 
  cat >> $TARGET <<- EOF
refclock SHM 0 poll 3 refid GPS0
makestep 2 3
allow all
local stratum 10
EOF
elif [ "$RPITYPE" = "master" ]
then
  cat >> $TARGET <<- EOF
server 192.168.0.202 iburst offset 0.5
server 192.168.0.212 iburst prefer offset 0.5
local stratum 10
EOF
fi
# To be finished
#
################################################################################